### ISSUE TITLE
DemoExampleMaker Widget Updates

### ISSUE THREAD

**Issue by nbriz** [netizenorg/netnet.studio#212]
opening this issue to keep track of the various update @Cthomp7 is working on for this widget:
- [x] step "preview" button
- [x] "upload json" button ([more info here](https://github.com/netizenorg/netnet.studio/issues/177))
- [x] auto-update steps (instead of having to press the "update step" button)
- [x] replace `<textarea>` for the step with an instance of the netitor (so we can get syntax highlighting in there)
- [x] we should make the DemoMaker findable in the search bar (changed [listed](https://github.com/netizenorg/netnet.studio/blob/fd71acd7c99eca82702600236051a74babc27e09/www/widgets/DemoExampleMaker.js#L6) to `true`)
- [x] toc (table on contents property) [needs work](https://github.com/netizenorg/netnet.studio/issues/216)
- [x] the example numbering (id/key) also [needs some work](https://github.com/netizenorg/netnet.studio/issues/218)
- [x] create convo file for this widget (start with confirmation dialogue before uploading a new json)

**Comment by nbriz** [comment]
@Cthomp7 
so u know how entering line numbers u want to have highlighted need to be comma separated, for ex `5,6,7,8` would highlight lines 5-8 in that particular step? what do u think about adding some functionality so that if there is a '-' present, it highlights a range instead of individual lines, so that we could write something like `5-8` instead? or maybe even something like `5-8,10-12`?

**Comment by nbriz** [comment]
@Cthomp7 also, as i'm working on new examples using the latest version of the Demo/Example Maker, i'm noticing a bug where the description i add to the first example wont' auto-save unless i also change the title of the step from the default "getting started" to something else

**Comment by nbriz** [comment]
...ok, as i keep working on this example i'm noticing lots of save bugs, when i go back to edit previous steps && then switch to another step, when i switch back to the former step it turns out not to have saved my change. i end up having to edit the description multiple times (also editing the name + other fields just to try && force the widget to auto-save)... hard to tell exactly why/when it doesn't save my change.

**Comment by nbriz** [comment]
moved the remaining bits to their own tasks so we can merge these updates + close this issue!
-  [DemoExampleMaker: re-order steps functionality #236](https://github.com/netizenorg/netnet.studio/issues/236)
- [DemoExampleMaker: Bugs + Updates #237](https://github.com/netizenorg/netnet.studio/issues/237)
- [DemoExampleMaker: documentation #238](https://github.com/netizenorg/netnet.studio/issues/238)
